# Generated by Django 4.2.6 on 2023-10-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='account_number',
            field=models.CharField(default=2050, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_table',
            name='deposit_amount',
            field=models.CharField(default=2050, max_length=100),
            preserve_default=False,
        ),
    ]
